# Generated by Django 4.0.6 on 2022-09-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Food Items',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='foodItems',
            field=models.ManyToManyField(to='hotel.food'),
        ),
    ]
