# Generated by Django 4.0.6 on 2022-09-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='foodItems',
            field=models.ManyToManyField(blank=True, to='hotel.food'),
        ),
    ]
