# Generated by Django 4.0.6 on 2022-09-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_clients_fooditems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='clients',
            name='identity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
