# Generated by Django 4.0.6 on 2022-09-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_clients_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.clients')),
                ('orderedItems', models.ManyToManyField(to='hotel.food')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
