# Generated by Django 4.0.6 on 2022-09-13 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderedItems',
        ),
        migrations.AddField(
            model_name='order',
            name='orderedItems',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.food'),
            preserve_default=False,
        ),
    ]
